export const LS_KEY = 'storage'
export const PORTFOLIO_MAP_KEY = 'portfolioMap'
export const SESSION_PASSWORD_KEY = 'password'
export const PIN_KEY = 'passcode'
export const INSTALL_ID_STORE_KEY = 'installationId'
